"""Add missing job fields for admin endpoints

Revision ID: 9a7fb684b584
Revises: 148d0033867d
Create Date: 2025-07-09 08:30:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9a7fb684b584"
down_revision = "148d0033867d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add missing columns to transcription_jobs table
    op.add_column(
        "transcription_jobs",
        sa.Column("progress", sa.Float(), nullable=False, server_default="0.0"),
    )
    op.add_column(
        "transcription_jobs", sa.Column("task_id", sa.String(), nullable=True)
    )
    op.add_column(
        "transcription_jobs",
        sa.Column(
            "job_type", sa.String(), nullable=False, server_default="transcription"
        ),
    )
    op.add_column(
        "transcription_jobs", sa.Column("parameters", sa.JSON(), nullable=True)
    )
    op.add_column("transcription_jobs", sa.Column("result", sa.JSON(), nullable=True))
    op.add_column("transcription_jobs", sa.Column("error", sa.Text(), nullable=True))

    # Create index on task_id for performance
    op.create_index(
        "ix_transcription_jobs_task_id", "transcription_jobs", ["task_id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop index
    op.drop_index("ix_transcription_jobs_task_id", table_name="transcription_jobs")

    # Remove added columns
    op.drop_column("transcription_jobs", "error")
    op.drop_column("transcription_jobs", "result")
    op.drop_column("transcription_jobs", "parameters")
    op.drop_column("transcription_jobs", "job_type")
    op.drop_column("transcription_jobs", "task_id")
    op.drop_column("transcription_jobs", "progress")

    # ### end Alembic commands ###
