apiVersion: v1
kind: Secret
metadata:
  name: audio-processor-secrets
  namespace: audio-processor
type: Opaque
data:
  # Base64 encoded values for sensitive data
  SECRET_KEY: "eW91ci1zZWNyZXQta2V5" # "your-secret-key" base64 encoded
  DATABASE_URL: "cG9zdGdyZXNxbCthc3luY3BnOi8vdXNlcjpwYXNzd29yZEBsb2NhbGhvc3Q6NTQzMi9kYm5hbWU=" # "postgresql+asyncpg://user:password@localhost:5432/dbname" base64 encoded
  REDIS_URL: "cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OS8w" # "redis://localhost:6379/0" base64 encoded
  KEYCLOAK_URL: "aHR0cDovL2xvY2FsaG9zdDo4MDgw" # "http://localhost:8080" base64 encoded
  KEYCLOAK_REALM: "bWFzdGVy" # "master" base64 encoded
  KEYCLOAK_CLIENT_ID: "eW91ci1jbGllbnQtaWQ=" # "your-client-id" base64 encoded
  KEYCLOAK_CLIENT_SECRET: "eW91ci1jbGllbnQtc2VjcmV0" # "your-client-secret" base64 encoded
  HUGGINGFACE_TOKEN: "" # Your Hugging Face token (if applicable) base64 encoded
  CELERY_BROKER_URL: "cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OS8x" # "redis://localhost:6379/1" base64 encoded
  CELERY_RESULT_BACKEND: "cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OS8y" # "redis://localhost:6379/2" base64 encoded
  SUMMARIZATION_API_KEY: "" # Your summarization API key (if applicable) base64 encoded
