version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../..:/usr/src/app
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/audio_processor
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=master
      - KEYCLOAK_CLIENT_ID=audio-processor-api
      - KEYCLOAK_CLIENT_SECRET=your-client-secret
      - ENVIRONMENT=development

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=audio_processor
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  worker:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    command: celery -A app.workers.celery_app worker -l info
    volumes:
      - ../..:/usr/src/app
    depends_on:
      - redis
      - app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/audio_processor
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2

volumes:
  postgres_data:
