environment: development
debug: true
host: 0.0.0.0
port: 8000
log_level: INFO
enable_audio_upload: true
enable_url_processing: true
enable_translation: true
enable_summarization: true
max_file_size: 104857600
supported_formats:
  - wav
  - mp3
  - m4a
  - flac
  - ogg
  - opus
temp_dir: /tmp/audio_processor

database:
  url: postgresql://user:password@localhost:5432/db_name
  pool_size: 20

redis:
  url: redis://localhost:6379/0

auth:
  keycloak_url: http://localhost:8080/auth
  realm: master
  client_id: my_client
  client_secret: my_secret

whisperx:
  model_size: large-v2
  device: cpu
  compute_type: float32
  language: auto
  batch_size: 8

diarization:
  model_name: pyannote/speaker-diarization
  device: cpu

celery:
  broker_url: redis://localhost:6379/1
  result_backend: redis://localhost:6379/2

summarization:
  api_url: http://localhost:8001/summarize

# Graph database configuration
graph:
  enabled: true
  database:
    type: neo4j  # Supported: neo4j, arangodb
    url: bolt://localhost:7687
    username: neo4j
    password: password
    name: neo4j
    max_connection_lifetime: 1800
    max_connection_pool_size: 50
    connection_acquisition_timeout: 30
  processing:
    batch_size: 100
    extraction_queue: graph_extraction
    topic_extraction:
      method: keyword_matching
      keywords:
        technology: [ai, software, computer, digital, tech, algorithm, programming, code, data, cloud, machine, learning, neural, network, api, database, framework, platform, automation, integration]
        business: [revenue, profit, market, sales, budget, finance, investment, growth, strategy, customer, client, partnership, contract, proposal, roi, kpi, metrics, performance]
        meeting: [agenda, action, decision, follow-up, deadline, task, schedule, appointment, presentation, discussion, summary, notes, minutes, next, steps]
        project: [milestone, deliverable, timeline, scope, requirement, specification, development, testing, deployment, launch, phase, sprint, iteration, backlog]
        personal: [family, vacation, health, hobby, weekend, personal, break, time, off, holiday, sick, leave, appointment, doctor, dentist]
    entity_extraction:
      patterns:
        email: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
        phone: '\b\d{3}-\d{3}-\d{4}\b|\b\(\d{3}\)\s*\d{3}-\d{4}\b'
        date: '\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b'
        time: '\b\d{1,2}:\d{2}(?::\d{2})?\s*(?:AM|PM|am|pm)?\b'
        money: '\$\d+(?:,\d{3})*(?:\.\d{2})?|\b\d+(?:,\d{3})*(?:\.\d{2})?\s*(?:dollars?|USD)\b'
        url: 'https?://[^\s<>"{}|\\^`\[\]]*'
        mention: '@[a-zA-Z0-9_]+'
